import React,{useState}from'react'
import{createRoot}from'react-dom/client'
import{Home,Users,ClipboardList,Star,Euro,PlaySquare,Menu,Bell,UserCircle,Cloud,FileDown,ChevronRight,Search,CalendarDays,Trophy,Target,Eye,BarChart3}from'lucide-react'
import{signInGoogle,createDriveFolder,uploadPdfToDrive}from'./services/google.js'
import{exportElementToPdf}from'./services/pdf.js'
import'./styles.css'
const tabs=[{"id": "dashboard", "label": "Início", "icon": "🏠"}, {"id": "athletes", "label": "Atletas", "icon": "👥"}, {"id": "training", "label": "Treinos", "icon": "📅"}, {"id": "eval", "label": "Avaliação", "icon": "⭐"}, {"id": "more", "label": "Mais", "icon": "☰"}]
const sections={"dashboard": {"title": "Dashboard Treinador", "subtitle": "Treinos, atletas, alertas e Google Drive/Sheets.", "cards": [{"title": "Atletas", "text": "Futsal, futebol, voleibol, formação e seniores."}, {"title": "Treinos", "text": "Sessões, microciclos, mesociclos e macrociclos."}, {"title": "Avaliações", "text": "Técnica, tática, física e mental."}, {"title": "Scouting", "text": "Disponível nos seniores."}], "items": ["Plano de treino por escalão", "Vídeos e animações partilhadas", "PDF do plano de treino", "Scouting seniores"]}, "athletes": {"title": "Atletas", "subtitle": "Gestão técnica do plantel por modalidade e escalão.", "cards": [{"title": "Futsal", "text": "Sub-7 a Seniores."}, {"title": "Futebol", "text": "Sub-7 a Seniores."}, {"title": "Voleibol", "text": "Minis a Seniores."}, {"title": "Perfil", "text": "Ficha individual do atleta."}], "items": ["Perfil completo", "Presenças", "Avaliação individual", "Relatório PDF"]}, "training": {"title": "Treinos", "subtitle": "Planeamento anual, mensal e semanal.", "cards": [{"title": "Macrociclos", "text": "Planeamento da época."}, {"title": "Mesociclos", "text": "Blocos de desenvolvimento."}, {"title": "Microciclos", "text": "Planeamento semanal."}, {"title": "Sessões", "text": "Exercícios, vídeos e PDF."}], "items": ["Aquecimento", "Parte técnica", "Parte tática", "Jogo condicionado"]}, "eval": {"title": "Avaliação", "subtitle": "Escala de 1 a 5 e gráficos de evolução.", "cards": [{"title": "Técnica", "text": "Passe, receção, remate, drible."}, {"title": "Tática", "text": "Posicionamento, leitura e decisão."}, {"title": "Física", "text": "Velocidade, resistência, força."}, {"title": "Mental", "text": "Disciplina, liderança, concentração."}], "items": ["Avaliação trimestral", "Relatório por atleta", "Relatório por escalão", "Guardar no Drive"]}, "more": {"title": "Ferramentas", "subtitle": "PDFs, Google e relatórios.", "cards": [{"title": "PDF", "text": "Treinos, avaliação, scouting."}, {"title": "Drive", "text": "Guardar documentos."}, {"title": "Sheets", "text": "Estatísticas e pagamentos."}, {"title": "Calendar", "text": "Treinos e jogos."}], "items": ["Banco de exercícios", "Biblioteca de vídeos", "Relatórios", "Configurações Google"]}}
function App(){const[tab,setTab]=useState(tabs[0].id);const[g,setG]=useState('offline');const[folder,setFolder]=useState(null)
async function connect(){try{setG('a ligar...'); await signInGoogle(); const f=await createDriveFolder('Cav Academy Coach'); setFolder(f); setG('ligado')}catch(e){console.error(e);setG('erro');alert('Verifica CLIENT_ID e API_KEY')}}
async function pdf(name='Cav_Academy_Coach.pdf'){try{const b=await exportElementToPdf('pdf-area',name); if(g==='ligado'){await uploadPdfToDrive(name,b,folder?.id); alert('PDF guardado no Drive')} else alert('PDF gerado. Liga ao Google para enviar ao Drive.')}catch(e){console.error(e);alert('Erro ao gerar PDF')}}
const cur=sections[tab]||sections[tabs[0].id]
return <div className="phone"><Header g={g} connect={connect}/><main id="pdf-area"><section className="hero"><h2>{cur.title}</h2><p>{cur.subtitle}</p><button onClick={()=>pdf(cur.title+'.pdf')}><FileDown size={18}/> Gerar PDF</button></section><div className="grid">{cur.cards.map((c,i)=><Card key={i} item={c}/>)}</div><div className="list">{cur.items.map((it,i)=><Row key={i} text={it}/>)}</div></main><nav>{tabs.map(t=><button key={t.id} className={tab===t.id?'active':''} onClick={()=>setTab(t.id)}><span>{t.icon}</span><small>{t.label}</small></button>)}</nav></div>}
function Header({g,connect}){return <header><img src={`${import.meta.env.BASE_URL}logo-2you.png`}/><div><h1>CAV ACADEMY COACH</h1><p>TREINADOR</p></div><button className={g==='ligado'?'ok':''} onClick={connect}><Cloud size={18}/></button><Bell size={19}/><UserCircle size={22}/></header>}
function Card({item}){return <div className="card"><b>{item.title}</b><p>{item.text}</p></div>}
function Row({text}){return <div className="row"><div><b>{text}</b><p>Clique para consultar detalhes, PDF, Drive e histórico.</p></div><ChevronRight size={18}/></div>}
createRoot(document.getElementById('root')).render(<App/>)
